#!/bin/bash

###########################################################
#
#	These settings will be used for installtion
#
#	WARNING !!!!!!!!!!!!!!!!!
#
#	Some settings can be harmfull if they do not 
#	have the correct value. It is important to 
#	check this list and change if needed.
#
############################################################

DISK="sdc"
EFI="sdc1"
#BOOT="sdc2"
SWAP="sdc2"
ROOT="sdc3"
HOME="sdc4"

TIMEZONE="America/Los_Angeles"


