#!/bin/bash
. ./src/config
clear

echo -e "\e[1m\e[96mGentoo Installation Phase 1\e[0m"
echo -e "\e[93m"

cat <<EOF

##########################################################################
#
# Installatio phase one will install the base necessities to chroot into
# the system. 
# 
# - mount root partition
# - set time
# - download and install tarball
# - Set make.conf parameters
#
##########################################################################



EOF
echo -e "\e[0m"



# Choice: Move on or not
while true; do
    read -p "Do you wish to proceed? [Y/N]" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) 
	clear
	menu_main
break
	;;
        * ) echo "Please answer yes or no.";;
    esac
done
clear


# set system time
echo "Set time"
ntpd -q -g
echo " "


echo "mounting the root partition into /mnt/gentoo"
mount /dev/${ROOT} /mnt/gentoo
echo " "

# echo $PWD

# copy instal framework
echo "Copy installation help"
cp ./gentoo /mnt/gentoo
cp -a ./src /mnt/gentoo
cd /mnt/gentoo

echo " "

read -p "Next the links web browser will start to download the tarbal. Press enter to continue"

clear

links https://www.gentoo.org/downloads/mirrors/

clear

# read -p "Press enter to continue"
prompt="Please select the tarball file or other option:"
echo " "

options=( $(find -maxdepth 1 -print0 | xargs -0) )

PS3="$prompt "
select opt in "${options[@]}" "Quit" "Skip" ; do
    
    case $opt in
        'Skip')
            echo "skipping this step"
            break
        ;;
        'Quit')
            echo "quit and exit"
            exit
        ;;
        *)
            if ! { tar ztf "$opt" || tar tf "$opt"; } >/dev/null 2>&1; then
                echo "$opt is not a tar file"
            else
                tar xpvf $opt --xattrs-include='*.*' --numeric-owner
                break
            fi
        ;;
    esac
    
done

clear


read -p "Make channges to make.conf. Press enter to continue"
cat <<EOF
##########################################################################
# The make.conf file detemines teh configurattion used during the 
# merging process. It is recommended to configure the make.conf file 
# before installation. The configuration will be copied to the 
# make.conf in gentoo portage
# Throughout installation the make.comf file may change. 
#
##########################################################################
EOF

value=`cat ./src/make.conf`
echo "$value" > /mnt/gentoo/etc/portage/make.conf
nano -w /mnt/gentoo/etc/portage/make.conf

clear
read -p "Next choose the mirrors to download packages. Press enter to continue"
mirrorselect -i -o >> /mnt/gentoo/etc/portage/make.conf

# Chrooting
mkdir --parents /mnt/gentoo/etc/portage/repos.conf
cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf
cp --dereference /etc/resolv.conf /mnt/gentoo/etc/

clear

cat <<EOF

This part is done. Press enter to exit and restart the menu to chroot
into the system
# . gentoo

After chrooting you must agaion call the install helper menu with 
# . gentoo

Then start step 2

EOF

read -p ""
exit






