#!/bin/bash
. ./src/config
clear

echo -e "\e[1m\e[96mGentoo Installation Phase 1\e[0m"
echo -e "\e[93m"

cat <<EOF

##########################################################################
#
# Step 1 will install the Gentoo base setup for further installation
#
# This step will contain following:
# - download and install tarball
# - Set make.conf parameters
#
# Make sure all variables in the system are set correctly before 
# proceeding installation. Check menu selection 1.
# 
# To learn about the installation process, visit: https://wiki.gentoo.org/
#
##########################################################################



EOF
echo -e "\e[0m"

while true; do
    read -p "Do you wish to proceed? [Y/N]" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) menu_main;;
        * ) echo "Please answer yes or no.";;
    esac
done
clear


# set system time
echo "ntpd -q -g"
ntpd -q -g

echo " "
echo "mounting the root partition into /mnt/gentoo"
mount /dev/${ROOT} /mnt/gentoo

# echo $PWD

# copy instal framework
echo " "
echo "Copy installation command files"
cp ./gentoo /mnt/gentoo
cp -a ./src /mnt/gentoo
cd /mnt/gentoo

echo " "

read -p "Step1 is downloading and installing the tarbal. Press enter to continue"

clear

echo " "
echo "We will be downloading the stage 3 tarball."
echo " "

read -p "Press enter to launch the the links terminal web browser."

links https://www.gentoo.org/downloads/mirrors/

clear

# read -p "Press enter to continue"
echo " "
prompt="Please select the tarball file or other option:"
echo " "

options=( $(find -maxdepth 1 -print0 | xargs -0) )

PS3="$prompt "
select opt in "${options[@]}" "Quit" "Skip" ; do
    
    case $opt in
        'Skip')
            echo "skipping this step"
            break
        ;;
        'Quit')
            echo "quit and exit"
            exit
        ;;
        *)
            if ! { tar ztf "$opt" || tar tf "$opt"; } >/dev/null 2>&1; then
                echo "$opt is not a tar file"
            else
                tar xpvf $opt --xattrs-include='*.*' --numeric-owner
                break
            fi
        ;;
    esac
    
done

clear



cat <<EOF
##########################################################################
#
# Next step is setting the system flags. The settings are for
# an i7 CPU Sandy Bridge, Change as needed
#
##########################################################################
EOF

read -p "Press enter to continue"


value=`cat ./src/make.conf`
echo "$value" > /mnt/gentoo/etc/portage/make.conf
nano -w /mnt/gentoo/etc/portage/make.conf

clear

cat <<EOF
##########################################################################
#
# Next step is choosing download mirrors that we use to
# download packageds and updates. Choose mirrors that give
# a bbetter speed and download. Usually that will be the
# closets mirrors.
#
##########################################################################
EOF


read -p "Press enter to continue"


# Chrooting

mirrorselect -i -o >> /mnt/gentoo/etc/portage/make.conf
clear

mkdir --parents /mnt/gentoo/etc/portage/repos.conf

cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf

clear


cat <<EOF

Great!

At this point you have the base sustemn installed and you can come
back at any time by installing the your boot medium

Just remount your installation scripts and start the menu again

> . gentoo

The script will stop now and you must exit. Rastart the menu  and
chroot into gentoo. Then start step 2


If the Gentoo installation is interrupted anywhere after this point, it is
possible to 'resume' the installation at this step. 


EOF

read -p "Press enter to quit"
exit






