#!/bin/bash
cat <<EOF

##########################################################################
#
# In step 2 it will be determined what desktop profile will be used
# 
# - fetch portage snapshot
# - select a profile
# 
##########################################################################
EOF


. ./src/config
. /etc/profile
env-update

echo " "
echo "mounting boot patition"

if [ -z ${EFI+x} ]; 
then 
	echo "EFI is not set"; 
else 
        # mount /dev/${BOOT} /boot
	echo "'$EFI' is mounted in /boot"; 
fi

#read -p "Press enter to continue"
#exit;

mount /dev/${EFI} /boot

clear


echo -e "\e[93m"
echo -e "\e[1m\e[91m"
echo -e "\e[0m"
echo -e "\e[0m"


read -p "Press enter to install portage repository"
emerge-webrsync

eselect news read > ./src/news.txt

echo "SystemD from here"

read -p "Press enter and select Gnome/Systemd"






cat  <<EOF
This installation process is based on Gnome and SystemD. Choose the correct 
profile to facilitate this installation
EOF



############################################################################
# PROFILE SELECTION
#
# generate profile list and generate a selection menu
############################################################################
eselect profile list > ./src/file.txt
mapfile -t profileArray < ./src/file.txt

# unset first line
unset profileArray[0]

clear

selectprofile ()
{
 
    select option; do # in "$@" is the default
        if [ "$REPLY" -eq "$#" ];
        then
            echo "Exiting..."
            break;
        elif [ 1 -le "$REPLY" ] && [ "$REPLY" -le $(($#-1)) ];
        then
            echo "You selected option $REPLY"
            eselect profile set $REPLY
            break;
        else
            echo "Incorrect Input: Select a number 1-$#"
        fi
    done
}

selectprofile "${profileArray[@]}"

############################################################################

clear
cat <<EOF
##########################################################################
#
# Next we emerge into the Gentoo @world
#
# If a question is asked abiut merging updates, choose -3.
#
# It is advised to read up on use flags dependencies fopr teh program
# you're installing, but the initial install can;t be done without
# the first aceptance.
# Check the handbook for more on this subject.
#
# To accept and merge the changes issue following command:
#
# > etc-update
#
# Emerging your system can be a very long process depending on the
# profile chosen. It can take up hours and it is advised to do this
# when you can the computer for a long time
#
# If emereging gets interupted, it can be started again by running
#
# > ./emerge.world.sh
#
##########################################################################
EOF

read -r -p "Are you sure? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
    emerge --ask --verbose --update --deep --newuse @world
    etc-update
    
    #   emerge -v system/world/... --resume --verbose
    #   FEATURES="keepwork" emerge whatever
    
else
    exit
fi

#

#
