#!/bin/bash
. ./src/config
clear




cat <<EOF

Installing grub-efi in /boot

EOF

grub-install --target=x86_64-efi --efi-directory=/boot

echo 'efi grub installed'
read -p "Grub efi installed in boot. Enter to continue."

 menu_main


