#!/bin/bash
. ./src/config

mount /dev/${BOOT} /boot

clear

echo -e "\e[1m\e[96mGentoo Installation Phase 1\e[0m"
echo -e "\e[93m"

cat <<EOF

##########################################################################
#
# In step 2 it will be determined what desktop profile will be used
# 
# Step 2 contains teh following:
# - fetch portage snapshot
# - set and generate locales
# - select desktop profile
# 
# There will also be a news list generated. This news can be read 
# from the main menu 
#
# To learn more on teh Gentoo installation, please refere to the handbook.
# visit: https://wiki.gentoo.org/
#
##########################################################################


Configuring Portage
Installing an ebuild repository snapshot from the web


EOF

echo -e "\e[1m\e[91m"
cat <<EOF
WARNING: This step contains merging the profile. This can take up considerable 
time that can occupy the computer for several hours.
EOF
echo -e "\e[0m"
echo -e "\e[0m"


read -p "Press enter to continue"
emerge-webrsync

eselect news read > ./src/news.txt


read -p "Press enter to continue"

cat  <<EOF
Next choose the profiles
EOF


echo ${TIMEZONE} > /etc/timezone
emerge --config sys-libs/timezone-data
clear
nano -w /etc/locale.gen
locale-gen

cat <<EOF > /etc/env.d/02locale
LANG="en_US.UTF-8"
LC_COLLATE="C"
EOF

nano /etc/env.d/02locale



# eselect locale list > locales.txt

locale-gen

eselect profile list > ./src/file.txt


mapfile -t profileArray < ./src/file.txt


unset profileArray[0]
clear

selectprofile ()
{
 
    select option; do # in "$@" is the default
        if [ "$REPLY" -eq "$#" ];
        then
            echo "Exiting..."
            break;
        elif [ 1 -le "$REPLY" ] && [ "$REPLY" -le $(($#-1)) ];
        then
            echo "You selected option $REPLY"
            eselect profile set $REPLY
            break;
        else
            echo "Incorrect Input: Select a number 1-$#"
        fi
    done
}

selectprofile "${profileArray[@]}"


clear
cat <<EOF
##########################################################################
#
# Next we emerge into the Gentoo @world
#
# If a question is asked abiut merging updates, choose -3.
#
# It is advised to read up on use flags dependencies fopr teh program
# you're installing, but the initial install can;t be done without
# the first aceptance.
# Check the handbook for more on this subject.
#
# To accept and merge the changes issue following command:
#
# > etc-update
#
# Emerging your system can be a very long process depending on the
# profile chosen. It can take up hours and it is advised to do this
# when you can the computer for a long time
#
# If emereging gets interupted, it can be started again by running
#
# > ./emerge.world.sh
#
##########################################################################
EOF

read -r -p "Are you sure? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
    emerge --ask --verbose --update --deep --newuse @world
    etc-update
    
    #   emerge -v system/world/... --resume --verbose
    #   FEATURES="keepwork" emerge whatever
    
else
    exit
fi

#

#
