#!/bin/bash
. ./src/config


mapfile -t menu_array < ./src/menu_main_items
clear



selectkernel ()
{
    select opt in "$@" "Quit"  ; do
        
        case $opt in
            'configure install')
                nano -m ./src/config
                menu_main
                break
            ;;
            'preparing disk')
                cfdisk /dev/${DISK}
                menu_main
                break
            ;;
            
            'Linux Kernel')
                clear
                menu_kernel
                break
            ;;
            'install step 1')
                inst_step1
                break
            ;;
            'install step 2')
                inst_step2
                break
            ;;
            'chroot gentoo')
                inst_chroot
                break
            ;;
            'read news')
                nano ./src/news.txt
                menu_main
                break
            ;;
            
            
            'emerge world')
                echo "starting step 1"
                break
            ;;
            'install kernel')
                echo "starting step 1"
                break
            ;;
            'download tarball')
                echo "starting step 1"
                break
            ;;
            'read news')
                echo "starting step 1"
                break
            ;;
            'clean dir')
                echo "starting step 1"
                break
            ;;
            'configure kernel')
                echo "starting step 1"
                break
            ;;
            'read help')
                echo "starting step 1"
                break
            ;;
            'networking')
                echo "starting step 1"
                break
            ;;
            'conpile kernel')
                echo "starting step 1"
                break
            ;;
            'install initramfs')
                echo "starting step 1"
                break
            ;;
            'configure make.conf')
                nano ./src/make.conf
                break
            ;;
            'Quit')
                echo "quit and exit"
                exit
            ;;
            *)
                echo -e  "\e[91mInvalid option\e[0m"
                
            ;;
        esac
    done
}

selectkernel "${menu_array[@]}"
