#!/bin/bash
. ./src/config


mapfile -t menu_array < ./src/menu_main_items
# clear



selectkernel ()
{
    select opt in "$@" "Quit"  ; do
clear        
        case $opt in
            'edit install config')
                nano -m ./src/config
                clear
                menu_main
                break
            ;;
            'preparing disk')
                cfdisk /dev/${DISK}
                menu_main
                break
            ;;
            
            'edit make.conf')
                clear
                nano -m ./src/make.conf
                menu_main
                break
            ;;
            'install step 1')
                inst_step1
                break
            ;;
            'install step 2')
                inst_step2
                break
            ;;
            'chroot gentoo')
                inst_chroot
                break
            ;;
            'elect profile')
                clear
                inst_select_profile
                break
            ;;
            'Kernel menu')
                clear
                menu_kernel
                break
            ;;
            'Grub Install')
                clear
                inst_grub_install
                menu_main
                break
            ;;
     'grub-efi')
    if [[ "$PWD" = / ]]; then
                     inst_grub_efi
  clear
                    menu_main
                else
                    echo "not chrooted in gentoo"
                fi
               
                break
            ;;



            'Install help')
                input="./src/install_help_doc"
                nano $input
                menu_main
                break
            ;;
            'Grub Install Help')
                input="./src/grub_install_doc"
                nano $input
                menu_main
                break
            ;;
            'edit fstab')
                if [[ "$PWD" = / ]]; then
                    nano -m /etc/fstab
                    menu_main
                else
                    echo "not chrooted in gentoo"
                fi
                read -p "Press enter to continue"
                menu_main
                break
            ;;
            'read news')
                nano ./src/news.txt
                menu_main
                break
            ;;
            
            
            'emerge world')
                inst_emerge_world
                menu_main
                break
            ;;
            'install make.conf')
                if [[ "$PWD" = / ]]; then
                    nano -m /etc/fstab
                    menu_main
                    echo "Only available when not chrooted"
                else
                    inst_makeconf
                    echo "make.conf copied to gentoo"
                fi
                read -p "Press enter to continue"
                menu_main
                break
                break
            ;;
            'copy install files')
                inst_syscopy
                menu_main
                break
            ;;
            'download tarball')
                echo "starting step 1"
                break
            ;;
            'read news')
                echo "starting step 1"
                break
            ;;
            'clean dir')
                echo "starting step 1"
                break
            ;;
            'configure kernel')
                echo "starting step 1"
                break
            ;;
            'read help')
                echo "starting step 1"
                break
            ;;
            'networking')
                echo "starting step 1"
                break
            ;;
            'conpile kernel')
                echo "starting step 1"
                break
            ;;
            'install initramfs')
                echo "starting step 1"
                break
            ;;
            'configure make.conf')
                nano ./src/make.conf
                break
            ;;
            'Quit')
                echo "quit and exit"
                exit
            ;;
            *)
                echo -e  "\e[91mInvalid option\e[0m"
                menu_main
                break
            ;;
        esac
    done
}

selectkernel "${menu_array[@]}"
